import type { Ancestor } from "./types";

/** Last Signal's family tree: the films, books, and broadcasts it borrows from. */
export const lineage: Ancestor[] = [
  {
    year: 1938,
    title: "The War of the Worlds",
    by: "Orson Welles, CBS radio",
    medium: "radio",
    took: "Proof that a voice on the radio can make you believe anything. Last Signal promises to use this power responsibly.",
    color: "tomato",
  },
  {
    year: 1949,
    title: "Kaleidoscope",
    by: "Ray Bradbury",
    medium: "story",
    took: "A crew blown apart in space, drifting away from each other, still talking on the radio. The saddest open channel in fiction.",
    color: "sun",
  },
  {
    year: 1961,
    title: "Solaris",
    by: "Stanisław Lem",
    medium: "book",
    took: "Contact as a mirror. What you say to the unknown says more about you than about it.",
    color: "teal",
  },
  {
    year: 1967,
    title: "Kinoautomat",
    by: "Radúz Činčera, Expo 67",
    medium: "film",
    took: "The first interactive film. The audience voted with red and green buttons on their seats. We swapped the buttons for your voice.",
    color: "pink",
  },
  {
    year: 1968,
    title: "2001: A Space Odyssey",
    by: "Stanley Kubrick",
    medium: "film",
    took: "HAL taught everyone that the calmest voice on the ship is the one to worry about. ARC took notes.",
    color: "tomato",
  },
  {
    year: 1974,
    title: "The Conversation",
    by: "Francis Ford Coppola",
    medium: "film",
    took: "A whole movie that happens in the ears. Gene Hackman replaying one tape until it undoes him.",
    color: "cobalt",
  },
  {
    year: 1979,
    title: "Alien",
    by: "Ridley Scott",
    medium: "film",
    took: "MOTHER's Special Order 937: crew expendable. ARC's quiet course correction is a family tradition.",
    color: "plum",
  },
  {
    year: 1997,
    title: "Contact",
    by: "Robert Zemeckis, from Carl Sagan",
    medium: "film",
    took: "Headphones, a dish in the desert, and someone who will not stop listening. Our dish is in the Atacama.",
    color: "sun",
  },
  {
    year: 1998,
    title: "Story of Your Life",
    by: "Ted Chiang",
    medium: "story",
    took: "Language changes the person who learns it. Ines changes depending on how you talk to her.",
    color: "teal",
  },
  {
    year: 2009,
    title: "Moon",
    by: "Duncan Jones",
    medium: "film",
    took: "One worker, one machine, a long shift, and a twist about who the company thinks is replaceable.",
    color: "cobalt",
  },
  {
    year: 2013,
    title: "Gravity",
    by: "Alfonso Cuarón",
    medium: "film",
    took: "Ryan Stone reaches a fisherman in Greenland who cannot understand a word she says. In Last Signal, the stranger on the radio is you, and you can.",
    color: "pink",
  },
  {
    year: 2013,
    title: "Her",
    by: "Spike Jonze",
    medium: "film",
    took: "You can feel close to a voice. Ines would like it on the record that she is not looking for that.",
    color: "tomato",
  },
  {
    year: 2018,
    title: "Bandersnatch",
    by: "Black Mirror, Netflix",
    medium: "tv",
    took: "Choices on a remote. Ines would rather you just tell her what you think.",
    color: "plum",
  },
];
