import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "last-signal",
    title: "Last Signal",
    hook: "An interactive short film where a stranded astronaut can only talk to you, and what you say decides whether her crew comes home.",
    status: "in-production",
    date: "2026-10-16",
    flagship: true,
    hero: { kind: "placeholder", label: "Film in production" },
    areas: [
      "storytelling",
      "image-video",
      "dynamic-narrative",
      "conversational",
      "voice",
      "music",
      "games",
      "writing",
      "web-apps",
    ],
    tools: [
      { name: "Veo 3.1" },
      { name: "Kling" },
      { name: "ElevenLabs Eleven v4" },
      { name: "GPT-Live-1" },
      { name: "Suno v5.5" },
      { name: "Lyria 3 Pro" },
      { name: "Studio OS" },
    ],
    how: [
      "48 generated shots across three acts, three spoken decisions, and three endings. Any one viewing plays about 35 of them.",
      "The film pauses when Ines needs an answer. You reply out loud over a full-duplex voice link, and she can interrupt you back.",
      "A character agent scores every exchange on trust and nerve. Those two values, not keywords, choose the ending.",
      "The score is three stem layers mixed live by the branch engine, built from the radio's own carrier tone and static.",
    ],
    proof: [],
    next: "Interactive film has always been a menu bolted onto a movie. Voice makes the choice feel like a conversation, which is the first version of this format that I would actually want to watch twice.",
  },
  {
    slug: "studio-os",
    title: "Studio OS",
    hook: "An open-source agentic film studio: the writers' room, shot generation, and the editor agent that made Last Signal.",
    status: "in-production",
    date: "2026-10-15",
    flagship: true,
    hero: { kind: "placeholder", label: "Agent run graph coming soon" },
    areas: ["agents", "coding", "productivity", "storytelling"],
    tools: [
      { name: "Claude Agent SDK" },
      { name: "MCP" },
      { name: "Veo 3.1" },
      { name: "Kling" },
    ],
    how: [
      "A shot list goes in; generation jobs, reviewed takes, and an assembled cut come out.",
      "Separate agents plan shots, generate, review takes against the character and look references, and edit.",
      "Every tool is an MCP server, so the same studio runs from any MCP client.",
    ],
    proof: [],
    next: "Video generation got good in 2025. The bottleneck moved to editing and judgment, which is exactly the work agents are now ready to take on.",
  },
  {
    slug: "perihelion-set",
    title: "Walk the Perihelion",
    hook: "The ship from Last Signal as a persistent 3D world you can explore in the browser.",
    status: "planned",
    date: "2026-10-13",
    hero: { kind: "placeholder", label: "Set in production" },
    areas: ["3d", "world-models"],
    tools: [{ name: "World Labs Marble" }],
    how: [
      "Generated from the film's look frames, then used as the reference set for camera moves.",
    ],
    proof: [],
    next: "The set used to be built after the storyboard. Now the set is the storyboard.",
  },
  {
    slug: "drift",
    title: "Drift",
    hook: "Sixty playable seconds outside the Perihelion's hull, generated by a world model.",
    status: "planned",
    date: "2026-10-13",
    hero: { kind: "placeholder", label: "Playable moment in production" },
    areas: ["world-models", "games"],
    tools: [{ name: "Project Genie" }],
    how: [
      "Genie sessions cap at 60 seconds at 720p, so the piece is designed as one short, complete moment.",
    ],
    proof: [],
    next: "World models are short-lived today. Designing for that constraint is how to make them feel intentional.",
  },
  {
    slug: "agent-desk",
    title: "Agent Desk",
    hook: "A research, risk, and execution agent team trading a paper book, with every decision and its reasoning in public.",
    status: "planned",
    date: "2026-10-15",
    hero: { kind: "placeholder", label: "Desk starting up" },
    areas: ["quant", "agents"],
    tools: [{ name: "Firefolio", url: "https://www.firefolio.com/" }],
    how: [
      "Built on Firefolio's market data and trade replay.",
      "Paper money only. Every order shows the research and risk reasoning behind it.",
    ],
    proof: [],
    next: "Trust in an agent desk comes from legibility, not returns. Show the reasoning first.",
  },
];

export const flagships = projects.filter((p) => p.flagship);

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function projectsForArea(slug: string): Project[] {
  return projects.filter((p) => p.areas.some((a) => a === slug));
}
