/**
 * Converts the original 2015 to 2020 posts in src/content/archive/*.md into
 * src/content/archive-posts.ts, so pages need no file reads at runtime.
 * Run with: bun run archive
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { marked } from "marked";

const dir = join(process.cwd(), "src/content/archive");
const out = join(process.cwd(), "src/content/archive-posts.ts");

type Post = {
  slug: string;
  oldPath: string;
  date: string;
  title: string;
  tags: string[];
  html: string;
};

function frontmatter(src: string) {
  const m = src.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error("missing frontmatter");
  const data: Record<string, string> = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i > 0) data[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { data, body: m[2] };
}

const unquote = (s: string) => s.replace(/^["']|["']$/g, "");

function embed(src: string) {
  return `<div class="embed"><iframe src="${src}" title="Video" loading="lazy" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>`;
}

const posts: Post[] = readdirSync(dir)
  .filter((f) => f.endsWith(".md"))
  .sort()
  .reverse()
  .map((file) => {
    const date = file.replace(".md", "");
    const { data, body } = frontmatter(readFileSync(join(dir, file), "utf8"));
    const tags = (data.tags ?? "")
      .replace(/[[\]']/g, "")
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean);

    const md = body
      // Gatsby's `youtube:URL` shortcode.
      .replace(/`youtube:(\S+?)`/g, (_, url) => embed(url))
      // Raw iframes: drop fixed sizes, make responsive.
      .replace(/<iframe[^>]*src="([^"]+)"[^>]*><\/iframe>/g, (_, url) => embed(url))
      // Relative images were converted to webp under public/archive.
      .replace(/!\[([^\]]*)\]\(\.?\/?([\w-]+)\.(png|jpe?g|gif)\)/g, (_, alt, name) => `![${alt}](/archive/${date}-${name}.webp)`);

    let html = marked.parse(md, { async: false }) as string;
    // Every outbound link opens in a new tab.
    html = html.replace(/<a ([^>]*?)href="(https?:\/\/[^"]+)"([^>]*)>/g, (_, pre, href, post) => {
      const rest = `${pre} ${post}`.replace(/\s*(target|rel)="[^"]*"/g, "").trim();
      return `<a href="${href}"${rest ? ` ${rest}` : ""} target="_blank" rel="noopener noreferrer">`;
    });
    html = html.replace(/<img /g, '<img loading="lazy" ');

    return {
      slug: unquote(data.slug ?? data.path.replace("/", "")),
      oldPath: unquote(data.path),
      date,
      title: unquote(data.title),
      tags,
      html,
    };
  });

writeFileSync(
  out,
  `// Generated by scripts/build-archive.ts from src/content/archive/*.md. Do not edit.\n\nexport type ArchivePost = {\n  slug: string;\n  oldPath: string;\n  date: string;\n  title: string;\n  tags: string[];\n  html: string;\n};\n\nexport const archivePosts: ArchivePost[] = ${JSON.stringify(posts, null, 2)};\n`,
);
console.log(`Wrote ${posts.length} posts`);
